### ISSUE TITLE
Component Spec

### ISSUE THREAD

**Issue by yiminghe** [react-component/tree#1]
## 功能

- 支持多选，单选
- 支持键盘操作

## 使用示例

```js
var tree = <Tree defaultCheckedKeys={['1','2-1']}>
<TreeNode title="1"  key='1'/>
<TreeNode title='2' key='2'>
<TreeNode title='2-1' key='2-1' />
</TreeNode>
</Tree>
```

### Tree

<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th style="width: 100px;">name</th>
        <th style="width: 50px;">type</th>
        <th style="width: 50px;">default</th>
        <th>description</th>
    </tr>
    </thead>
    <tbody>
        <tr>
          <td>className</td>
          <td>String</td>
          <td></td>
          <td>多余的根部样式</td>
        </tr>
        <tr>
          <td>prefixCls</td>
          <td>String</td>
          <td>rc-tree</td>
          <td>前缀样式</td>
        </tr>
        <tr>
            <td>showLine</td>
            <td>Boolean</td>
            <th>false</th>
            <td>是否显示连接线</td>
        </tr>
        <tr>
            <td>checkable</td>
            <td>Boolean</td>
            <th>false</th>
            <td>是否允许多选</td>
        </tr>
        <tr>
            <td>checkedKeys</td>
            <td>String[]</td>
            <th>[]</th>
            <td>当前选中的节点</td>
        </tr>
        <tr>
            <td>defaultCheckedKeys</td>
            <td>String[]</td>
            <th>[]</th>
            <td>初始选中的节点</td>
        </tr>
        <tr>
            <td>defaultExpandedKeys</td>
            <td>String[]</td>
            <th>[]</th>
            <td>初始展开的节点</td>
        </tr>
        <tr>
            <td>onCheck</td>
            <td>function({checked,node,key})</td>
            <th></th>
            <td>选中一个节点时调用</td>
        </tr>
    </tbody>
</table>

### TreeNode

<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th style="width: 100px;">name</th>
        <th style="width: 50px;">type</th>
        <th style="width: 50px;">default</th>
        <th>description</th>
    </tr>
    </thead>
    <tbody>
        <tr>
          <td>className</td>
          <td>String</td>
          <td></td>
          <td>节点的多余样式</td>
        </tr>
        <tr>
            <td>disabled</td>
            <td>Boolean</td>
            <th>false</th>
            <td>是否禁用</td>
        </tr>
        <tr>
            <td>key</td>
            <td>Object</td>
            <th></th>
            <td>用于 selectedKeys 指定选中节点</td>
        </tr>
        <tr>
            <td>title</td>
            <td>React Element</td>
            <th></th>
            <td>节点的显示内容</td>
        </tr>
        <tr>
            <td>children</td>
            <td>TreeNode[]</td>
            <th></th>
            <td>子节点</td>
        </tr>
    </tbody>
</table>

##  参考
- kissy tree: https://github.com/modulex/tree
- rc-menu: https://github.com/react-component/menu

**Comment by warmhug** [comment]
ok

**Comment by warmhug** [comment]
感觉 ztree 的标签语义化（使用ul、li、a、span等）上做的更好些，kissy tree为什么不这么做？  

![2015-04-12 10 16 35](https://cloud.githubusercontent.com/assets/2011119/7104133/68a74cca-e0fd-11e4-9cf4-0143b979b424.png)

**Comment by yiminghe** [comment]
我不在乎语义化，只在乎功能

**Comment by yiminghe** [comment]
1. 去除 expandAll 属性，这是动作，不是属性，可以实现为方法递归设置treenode 的 expanded 属性
2.  checked selected 合二为一，去除 treeNode 的 checked defaultChecked 属性，顶层控制

**Comment by Sean-Snow** [comment]
请问下，我想实现动态更改checked 的数据怎么做，defaultCheckedKeys 的值是异步从服务端加载的，我把defaultCheckedKeys的值用state来做，没什么效果

**Comment by yiminghe** [comment]
@warmhug 实现 checkedKeys/selectedKeys 吧

**Comment by warmhug** [comment]
@Sean-Snow @yiminghe 已修复，增加checkedKeys/selectedKeys。参考：[demo](http://react-component.github.io/tree/examples/checked.html)
