### ISSUE TITLE
Regarding Upgradation

### ISSUE THREAD

**Issue by yadavsunil00001** [react-component/tree#104]
Hi, am using your application in my project. It seems that you are using the old style of react programming to build this  awesome application. After sometime react stop supporting this style of programming like createClass method and all. So my question is are you planning to upgrade node_module code or that going to valid no matter the version changes.

**Comment by paranoidjk** [comment]
just upgrade to latest version.

**Comment by yadavsunil00001** [comment]
My json file have many more entries other than text and id. I also want to use entries like taxonid, data-taxonid apart from text and id. Is there any way by which i get entries like id, taxon_id, text upon onClick.
My json look like this.
[
{
id: "122888",
parent: "#",
text: "Chromista",
icon: false,
speciesid: -1,
taxonid: 122888,
classsystem: 265799,
rank: 0,
type: "0",
isSpecies: false,
usersList: [ ],
isContributor: false,
position: "WORKING",
state: {
opened: false,
loaded: false,
disabled: false
},
haspermission: false,
li_attr: [ ],
a_attr: {
class: "WORKING",
data-taxonid: 122888
}
},
.
.
.]
I
