### ISSUE TITLE
How to get the parent node of a specific node.

### ISSUE THREAD

**Issue by Anuj16** [react-component/tree#105]
Hi All,

I am new to this tree component. I am not able to find the parent node of a particular node. I went through all the props method available for the node but no luck there.

Can anyone please help me out here ?

Thanks a lot in advance.

**Comment by chiragswadia** [comment]
I am facing the same issue. Can anyone please help?

**Comment by benjycui** [comment]
We are not going to provide API to get parent of a node, but you can calculate it by yourself.
