### ISSUE TITLE
Unexpected selecting when right click tree node

### ISSUE THREAD

**Issue by afc163** [react-component/tree#114]
https://github.com/react-component/tree/commit/1d4df8f96e45db22a0bbcc17deabee19797c8868##commitcomment-23809154

**Comment by afc163** [comment]
https://codepen.io/yuehui/pen/PKaqyy?editors=0011

**Comment by warmhug** [comment]
https://github.com/react-component/tree/commit/1d4df8f96e45db22a0bbcc17deabee19797c8868##commitcomment-23809387
