### ISSUE TITLE
Drag&Drop breaks Checkable

### ISSUE THREAD

**Issue by KaiVolland** [react-component/tree#117]
The `checkable` functionality does not work when the tree is `draggable`.

**Version:**
1.7.3

**Steps to reproduce:** 

1. Starting with the draggable example, just add the `checkable` property to the Tree in the render method.
2. Run the example.
3. Check any node (e.g. 0-0-0-0).
4. Drag it anywhere (e.g. under 0-0-0-1)
5. Try to uncheck the node. Try to check the node at the dragged node old position.

**What is expected:**

The dragged node can not be checked/unchecked.
The node at the dragged node old position can not be checked/unchecked.

**What is actually happening:**

The affected nodes can not be checked or unchecked.

**Comment by KaiVolland** [comment]
I  adde a tiny PR that fixed the issue for me.

I'm not 100% sure how much this will affect the performance but I didn't came to a smarter solution for now...

**Comment by benjycui** [comment]
> Starting with the draggable example, just add the checkable property to the Tree in the render method.

Do you mean this http://react-component.github.io/tree/examples/draggable.html ?

Please provide a re-producible demo: https://codepen.io/anon/pen/xLbmKm?editors=0010

**Comment by benjycui** [comment]
I know what happen.

**Comment by KaiVolland** [comment]
Unfortunately i can't get codepen running with the provided link as the provided link to rc-tree is broken [https://unpkg.com/rc-tree@1.7.3/dist/index.js](https://unpkg.com/rc-tree@1.7.3/dist/index.js) and the `/lib/index.js` uses ES6.

Nevertheless as you did see the problem you might want to check #118 again. This fixed the issue for me.

**Comment by benjycui** [comment]
I fixed this locally, but need more time to refactor rc-tree.
