### ISSUE TITLE
Is that possible to scroll to selected node in tree.

### ISSUE THREAD

**Issue by yadavsunil00001** [react-component/tree#127]
Hi, i just want to know, is that possible to scroll to selected node in rc-tree.

**Comment by benjycui** [comment]
You can use [dom-scroll-into-view](https://github.com/yiminghe/dom-scroll-into-view) to do so.

**Comment by AmagiDDmxh** [comment]
Since now tree provide a scrollTo ref method, should we reopen this and enable this feature now?
