### ISSUE TITLE
Check and uncheck controlled TreeSelect have different behavious

### ISSUE THREAD

**Issue by afc163** [react-component/tree#129]
![kapture 2017-09-14 at 16 38 26](https://user-images.githubusercontent.com/507615/30420423-1b2275a4-996c-11e7-8d8e-f8987729d27d.gif)

https://ant.design/components/tree/#components-tree-demo-basic-controlled

**Comment by afc163** [comment]
![spin](https://user-images.githubusercontent.com/507615/30420861-83138904-996d-11e7-8f75-b166517e69e1.gif)

另一个问题是，当我选中了 disabled 元素的父元素，disabled 元素的子元素就不能勾选了。没选的时候可以。

**Comment by jamespero** [comment]
I don't know if this is related, but I'm also seeing issues with the parent node checkbox checking disabled children who also have their checkboxes disabled.

**Comment by zombieJ** [comment]
Check conduct logic align in `1.8.0`
