### ISSUE TITLE
Drag & drop not accurate

### ISSUE THREAD

**Issue by bkniffler** [react-component/tree#132]
Hey, 
The drag&drop functionality is very frustrating to use for users, it doesn't work very accurately, especially when you try to move a node to the beginning/end of a parent. Just check the https://ant.design/components/tree/ demo and try to play around with drag/drop. 

I understand it is not very trivial to implement, but if its there, I'd expect it to work better.

**Comment by benjycui** [comment]
I don't understand, could you provide more details or just a PR to show what do you expect?

**Comment by jingling2009** [comment]
![image](https://user-images.githubusercontent.com/3634667/35085103-0c07aeaa-fc62-11e7-9ded-376eede7cf9a.png)

I try,and i know bkniffler's mean. For example just like the picture,i want to  drag the last node "0-2-label" to the forefront,i tried many times ,only one time success. It seams the drag node location has error.

**Comment by meglio** [comment]
I can reproduce this issue too:

![image](https://user-images.githubusercontent.com/282177/37445109-c70a0e08-2865-11e8-94eb-074f6e8fc8fe.png)

In your demo, try to drag the 0-2-label to the very top and then release it there - it won't move. What I expect is that it moves above the `0-0-label` folder.

**Comment by zombieJ** [comment]
Tested in draggable example. It's a bug, let me check.
Thanks for report.

**Comment by zombieJ** [comment]
fix line display on code refactor: https://github.com/react-component/tree/pull/149
Will adjust check range to make more user friendly.

**Comment by zombieJ** [comment]
update in 1.8.1
