### ISSUE TITLE
support for React v16

### ISSUE THREAD

**Issue by kenyxy** [react-component/tree#135]
Hello Team,
I just upgrade React to version 16, and rc-tree (rc-animate) run into error as below screenshot. 
can you please help on this?

![2017-09-29_20-11-38](https://user-images.githubusercontent.com/8474755/31015570-60d63be2-a553-11e7-89ab-b241b405e9fd.png)

**Comment by benjycui** [comment]
It had been fix, just make sure that you haven't lock dependencies and reinstall dependencies.
