### ISSUE TITLE
showIcon doesnt change the default folder icon for TreeNode

### ISSUE THREAD

**Issue by Tech-Admirer** [react-component/tree#136]
Need to change the default folder icon for treenode..
I have used many treenodes . Added showIcon property for Tree tag and icon tag for treenode.
But it doesn't change the folder icon.

Tried the following

import React, { Component } from 'react';
import './App.css';
import { Icon } from 'antd';
import { DatePicker } from 'antd';
import { Tree } from 'antd';
import { LocaleProvider } from 'antd';
import enUS from 'antd/lib/locale-provider/en_US'
import classNames from 'classnames';

const TreeNode = Tree.TreeNode;

class MyTree extends React.Component {
	
  constructor(props)
  {
	super(props);
	this.state = { selectedCar: "",selectedDate: ""}
  }
	
	
	
  onSelect = (selectedKeys, info) => {
  console.log('selected', selectedKeys, info);
	if ( this.state.selectedCar !== ".")
	{
	this.setState({selectedCar: info.node.props.title});
	console.log("----------------")
	}

  }
  
  
  onChange = (dates, datestrings ) => {
    console.log("dates are", dates,datestrings);
	this.setState({selectedDate: datestrings})
  }
  
  
  
  render() {
	const i1=9
	
	if ( this.state.selectedCar !== "" && this.state.selectedDate !== "")
	{
		alert( "Your Car  "+ this.state.selectedCar+ " will be delivered on "+this.state.selectedDate);
	} 
    return (
	<LocaleProvider locale={enUS}>
	<div className="Business">
	<h2> Select a delivery date: </h2><DatePicker onChange={this.onChange}/>
	<h2> Select a car: </h2>
	<div className="Business">
	<Tree
        showLine
        defaultExpandedKeys={['0-0-0']}
        onSelect={this.onSelect}
		showIcon
      >
	  
        <TreeNode title={<h3><i>Vehicles</i></h3>} key="0-0">
          <TreeNode title={<h3><i>Sedan</i></h3>}  key="0-0-0">
            <TreeNode key="0-0-0-0" title={<h3><i><Icon type="car"/>Maruthi Ciaz</i></h3>} ></TreeNode>
            <TreeNode title={<h3><i><Icon type="car"/>Hyundai Verna</i></h3>} key="0-0-0-1" />
            <TreeNode title={<h3><i><Icon type="car"/>Ford Fiesta</i></h3>} key="0-0-0-2" />
			
    
          </TreeNode>
          <TreeNode title={<h3><i><Icon type="car"/>HatchBack</i></h3>} key="0-0-1">
            <TreeNode title={<h3><i><Icon type="car"/>Volks Polo</i></h3>} key="0-0-1-0" />
			<TreeNode title={<h3><i><Icon type="car"/>Hyundai i10</i></h3>} key="0-0-1-1" />
          </TreeNode>
          <TreeNode title={<h3><i><Icon type="car"/>XUV</i></h3>} key="0-0-2">
            <TreeNode title={<h3><i><Icon type="car"/>Xylo</i></h3>} key="0-0-2-0" />
            <TreeNode title={<h3><i><Icon type="car"/>Bretta</i></h3>} key="0-0-2-1" />
          </TreeNode>
        </TreeNode>
	
      </Tree>
	  </div>
       	  </div>
	  </LocaleProvider>

    );
  }
}

export default MyTree;

**Comment by Tech-Admirer** [comment]
I have read rc-tree-iconEle class can help.. but I can't find the details/API of this class, to usefor the above issue...

**Comment by benjycui** [comment]
I don't understand what you mean.

See: http://react-component.github.io/tree/examples/contextmenu.html

**Comment by Tech-Admirer** [comment]
Hi I need to change the default folder icon displaying for every treenode.
In the example, you had shared , it shows the default folder icon for every treenode..
I would like to show a customized icon instead of a folder icon.. 
How can i do it..

**Comment by benjycui** [comment]
> I need to change the default folder icon displaying for every treenode.

You need to override CSS.
