### ISSUE TITLE
onSelect node not getting checked 

### ISSUE THREAD

**Issue by yadavsunil00001** [react-component/tree#139]
onCheck it is specified in documentation that, either you select or check the node, the onCheck method get called, it seems like its not woking.

**Comment by benjycui** [comment]
Could you describe in details? Thanks.

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://codepen.io/anon/pen/xLbmKm?editors=0010

**Comment by yesmeck** [comment]
Closing since no response.
