### ISSUE TITLE
npm run dist not creating dist folder and files

### ISSUE THREAD

**Issue by hwernstrom** [react-component/tree#141]
I'm trying to create a umd distribution and the 'npm run dist' is not creating dist folder and files.

If I do the same thing with the react-component/slider it works. I do not see any differences in the way it creates the dist.

**Comment by benjycui** [comment]
Need to upgrade rc-tools https://github.com/react-component/tree/blob/master/package.json#L72

**Comment by paranoidjk** [comment]
@benjycui `npm owner add paranoidjk`

**Comment by paranoidjk** [comment]
@benjycui 这个要发个版本

**Comment by paranoidjk** [comment]
`+ rc-tree@1.7.10` done
