### ISSUE TITLE
Switcher can't click when parent disabled

### ISSUE THREAD

**Issue by valleykid** [react-component/tree#143]
Detail: https://github.com/ant-design/ant-design/issues/8591

**Comment by benjycui** [comment]
Ref: https://github.com/react-component/tree/issues/83#issuecomment-317969204

拆分多个属性吧，要一个 disabled 满足多种使用场景，不现实的。

**Comment by valleykid** [comment]
本来是新增个nodeDisabled属性的，与@afc163 讨论，还是放在一起。

**Comment by yesmeck** [comment]
嗯，我也觉得分开来比较合适。现在已经有 `selectable` 和 `checkable` 了。

**Comment by valleykid** [comment]
多一个属性 就多一些理解成本。虽然职责单一了，但一些场景需要组合配置多个属性，真的好吗？

**Comment by valleykid** [comment]
@afc163 觉得呢？

**Comment by afc163** [comment]
这里是有两个属性：

- nodeDisabled
- switcherDisabled

switcherDisabled 业务上感觉没有意义，就不做了。只保留 nodeDisabled，命名直接沿用现在的 disabled。

**Comment by valleykid** [comment]
目前的处理方式是 解除对switcher的限制，使其独立可用。我觉得**树节点可展开**是树结构的基本能力，不应该受到**是否可选择节点**的影响。

**Comment by yesmeck** [comment]
嗯，也有道理。

**Comment by valleykid** [comment]
Fixed by [antd@3.3.0](https://github.com/ant-design/ant-design/releases/tag/3.3.0).
