### ISSUE TITLE
设置checkStrictly时，checkedKeys中的halfChecked取值问题

### ISSUE THREAD

**Issue by snake2016** [react-component/tree#146]
设置checkStrictly时，点击子级中的某个值（还有未选中的兄弟节点），onselect 函数的第一个参数
 checkedKeys 中 halfChecked为空？？？  
个人理解此时halfChecked应该为父级的值吧

**Comment by zombieJ** [comment]
`checkStrictly`模式下，节点间没有关联因而父节点不会因为子节点checked而halfChecked。此处返回的`halfChecked`是为了和`checkedKeys` api mapping。
这的确有些让人疑惑
