### ISSUE TITLE
Switcher disappears when no data loads

### ISSUE THREAD

**Issue by project707** [react-component/tree#158]
If someone clicks an empty folder and no data is loaded for the tree within that, the switcher suddenly disappears. Taking away elements that were there is not good user experience - is there any way to turn this off?

**Comment by tdolphin** [comment]
Did you try explicitly setting isLeaf=false after failed load?

**Comment by 9walkStep** [comment]
Asyc loaded data ,if the getNodeState function return false,  the empty folder Icon style change 'duc'. but I think it is still folder Icon

**Comment by project707** [comment]
@tdolphin even with isLeaf=false it appears that the switcher element in the UI gets the "rc-tree-switcher-noop" class.

**Comment by zombieJ** [comment]
Updated in `1.11.3`.
When set `isLeaf` to `false` will trade Node as a folder whatever is empty.
