### ISSUE TITLE
loading gif with custom icons

### ISSUE THREAD

**Issue by tdolphin** [react-component/tree#160]
If use custom icons, the loading gif (rotating circle) will not show while dynamic loading.
The class for loading doesn't get added when the class for custom icon is used.

**Comment by zombieJ** [comment]
Thanks for feedback.
`rc-tree 1.11.2` provide `loading` prop when call with `icon` as function.

**Comment by minesunny** [comment]
> Thanks for feedback. `rc-tree 1.11.2` provide `loading` prop when call with `icon` as function.

cloud you make an example?
