### ISSUE TITLE
Can't use Icon property on TreeNode

### ISSUE THREAD

**Issue by Channa53** [react-component/tree#161]
Hi,
I'm trying to send icon to TreeNode and I get compilation error - "Property 'icon' deos not exist on type..."
seems like that PropTypes are not up to date .
Thanks!

**Comment by zombieJ** [comment]
which version do you use?

**Comment by Channa53** [comment]
@types/rc-tree: 1.10.0
rc-tree: 1.11.1

**Comment by zombieJ** [comment]
Since we don't own the repo of [types/rc-tree](https://github.com/DefinitelyTyped/DefinitelyTyped). Could you pls also create the issue to them?
