### ISSUE TITLE
Basic example error: '0-0-0-0' does not exist in the tree

### ISSUE THREAD

**Issue by zetekla** [react-component/tree#162]
'0-0-0-0' does not exist in the tree

I loaded the basic example and everything looks good except the console error.
I think when you set the defaultProps, your DOM tree is not ready yet.
It happens with Webpack on Dev environment.

```
static defaultProps = {
    keys: ['0-0-0-0'],
  };
```

**Comment by zombieJ** [comment]
Thanks for feedback. The second example in basic do not have the '0-0-0-0' tree node.
Example updated.
