### ISSUE TITLE
支持drop 任意 ReactNode到TreeNode上

### ISSUE THREAD

**Issue by xVanTuring** [react-component/tree#164]
能否添加支持，来使得onDrop能相应其它 ReactNode 放置到TreeNode上。
（测试了React-dnd包裹div作为title，但是似乎源代码里面对拖拽事件都stopPropagation了）

**Comment by zombieJ** [comment]
感谢反馈，不知是否有意愿发个 pr 呢？

**Comment by chenshuai2144** [comment]
我觉得你的这个想法特别棒！

**Comment by xVanTuring** [comment]
我还是选择用React-dnd自己做了一个树，rc-tree改动的话感觉会很麻烦.😉
![peek 2018-05-18 20-36](https://user-images.githubusercontent.com/11146248/40234945-31ba27e0-5adb-11e8-99c0-362070215127.gif)

**Comment by mraiguo** [comment]
@xVanTuring  您好，我想请问下，ie8不支持draggable是因为使用了onDrag事件吗？

**Comment by zombieJ** [comment]
@xVanTuring ， 恩 `onDrag` 是 IE 9 开始部分支持的。

**Comment by krizka** [comment]
Maybe it will help, I added PR #166 , which allows you to not apply `onDrag*` methods to tree node if `draggable={false}`, it helped us a lot it making draggable nodes with `react-dnd`
