### ISSUE TITLE
Is it impossible to use without .less?

### ISSUE THREAD

**Issue by Jongkeun** [react-component/tree#165]
Hi I'm a beginner at this project.
I run example of this project. Example was fine.
So I applied on my project.
![image](https://user-images.githubusercontent.com/33743343/40228362-0a0dbfb8-5acc-11e8-8957-be4c0403c06f.png)

But the result is this.
![image](https://user-images.githubusercontent.com/33743343/40228403-29eec46c-5acc-11e8-9142-5a0a17baf8ec.png)

I didn't use `less`.  I am using `.jsx` and `.css`.
I wanna use this project just import `import Tree, { TreeNode } from 'rc-tree';` without `less` files.
How can I use?
Let me know please.

**Comment by zombieJ** [comment]
`rc-tree` only provide the component. You can use any type css file you like:
https://codesandbox.io/s/0qmmm2jn2v
