### ISSUE TITLE
希望作者讲下设计思路

### ISSUE THREAD

**Issue by DavidSongzw** [react-component/tree#168]
最近在做一个 React Native 端的 Tree，看了作者的源码，感觉很复杂，希望您能讲讲自己的设计思路，谢谢。

**Comment by zombieJ** [comment]
Tree 里比较复杂的在于 checkable 下状态计算：
* 在 check 一个节点的时候，通过 conduct 将状态 向上/下 传导，等到传导到最顶端后收集 checked 节点触发事件
* 在作为可控组件时，同样对每个传入的 checked key 进行一次传导。如果传导过程中发现该节点已经是 checked 状态就停止以进行性能优化。

其他的主要是一些状态管理，来支持 可控/非可控 的切换。建议可以先从 select 开始看（搜索相关关键词）

**Comment by DavidSongzw** [comment]
OK 谢谢
