### ISSUE TITLE
Trigger expand

### ISSUE THREAD

**Issue by paulchan** [react-component/tree#17]
Hi, is it possible to trigger the expansion of the nodes in my code, given an eventKey?

**Comment by warmhug** [comment]
use `expandedKeys`

**Comment by paulchan** [comment]
I'm using the dynamic tree and I have called the onload method, how can I ensure that the state has changed before adding the target key to the expandedKeys?

**Comment by warmhug** [comment]
http://react-component.github.io/tree/examples/dynamic.html
![image](https://cloud.githubusercontent.com/assets/2011119/16518692/d442b7bc-3fb6-11e6-8208-228f9ef6f852.png)

**Comment by paulchan** [comment]
This is a portion of my get children code
```
    request.then((response) => {
      appendChildren(treeData, nodekey, response.data);
      this.setState({
        // expandedKeys: expandedKeys,
        treeData: treeData
      });
      this.setState( {'expandedKeys' : [nodekey] } );
    });
```

I can explicitly set the expandedKeys in the browser and sure enough, it did expand, but in this case it's not working.

**Comment by paulchan** [comment]
Resolved this. I did not add the props expandedKeys for the tree so it wasn't working.
