### ISSUE TITLE
Is it 'key' or 'eventKey' ?

### ISSUE THREAD

**Issue by oallouch** [react-component/tree#171]
Hi,
First of all, great tree !
If found in the code that the passed key to onExpand seems to be 'eventKey'.
I'm new to this lib et too shy to make a PR for the doc.
Should I do it ? :)

**Comment by zombieJ** [comment]
Hi @oallouch , thanks for feedback.

`key` is reserved prop in React. which will not pass into props for child component.
So we pass the `eventKey` to instead. It's by design  : )
