### ISSUE TITLE
Customize Tree Node Switcher Icon

### ISSUE THREAD

**Issue by Miteshdv** [react-component/tree#173]
Hi ,
 How we can customize Tree Node Switcher Icon , as of now i don't see any options.
Any work around please

Thanks

**Comment by Miteshdv** [comment]
Ok ,I forked the Tree and modified the code in renderSwitch Method is working now thanks.

**Comment by zombieJ** [comment]
Hi, you can use css to hide the switcher and use customize icon instead which also provide the `expanded` as prop.
