### ISSUE TITLE
webpack warning

### ISSUE THREAD

**Issue by ebar22** [react-component/tree#174]
hi,
when compiling we are getting the below warning, how can we handle it?

WARNING in ./~/css-loader?{"sourceMap":false}!./~/postcss-loader?{"sourceMap":true}!./~/resolve-url-loader?{"sourceMap":false}!./~/resolve-url-loader!./~/sass-loader!./~/rc-tree/assets/index.css
(Emitted value instead of an instance of Error)   resolve-url-loader cannot operate: source-map error
  cannot find one or more sources listed in the incoming source-map
 @ ./~/rc-tree/assets/index.css 4:14-219 13:2-17:4 14:20-225
 @ ./src/app/modules/formDesigner/components/newFormWizard/SelectedQueryDataPage.js
 @ ./src/app/modules/formDesigner/components/newFormWizard/WizardModal.js
 @ ./src/app/modules/formDesigner/formDesignerMain.js
 @ ./src/app/modules/wireFrame/constants.js
 @ ./src/app/modules/wireFrame/components/wireFrame.js
 @ ./src/app/modules/wireFrame/components/wireFrame-container.js
 @ ./src/app/modules/shared/router.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client? webpack/hot/dev-server ./src/index.js

**Comment by zombieJ** [comment]
Seems that your webpack loader config is not correct.

We only process the component issue here. For webpack usage, pls find help on stackoverflow: https://stackoverflow.com/
