### ISSUE TITLE
force busy indicator loading

### ISSUE THREAD

**Issue by ebar22** [react-component/tree#177]
hi,
i would like to know how can i force specific node to stop onLoadData, remove the busy indicator, collapse the node and allow user to expand manually and to expand node after that manually and fire the loadData event again?
i can't seems to find a way doing that, i'm entering to infinity calls to the server.

thanks in advance

**Comment by zombieJ** [comment]
You can use `loadedKeys` to control the treeNode loaded status

**Comment by zombieJ** [comment]
You can handle the timeout and return Promise.resolve. (Don't forget to set the loadedKeys at same time)
If user provided the `loadedKeys`, all the node load or not is controlled by the keys user provide. If you get infinity fetch, pls check the code logic for your processing the keys.
