### ISSUE TITLE
need a hover class

### ISSUE THREAD

**Issue by yuuk** [react-component/tree#183]
Need a hover class on tree item like:

![test](https://user-images.githubusercontent.com/9426456/43557674-602081a4-9638-11e8-9c46-87d1f2a1bfc3.png)

so that we can control the style easy.

**Comment by timothyallan** [comment]
Just came here checking if there was a way to do that. So far, overriding `.rc-tree li .rc-tree-node-content-wrapper` is working okay.

**Comment by zombieJ** [comment]
You can use pure css like:
.rc-tree li:hover > ...
