### ISSUE TITLE
dynamic render Tree

### ISSUE THREAD

**Issue by Leskd** [react-component/tree#184]
重现步骤：
   1. 动态加载树模式（默认只加载第一层树节点）
   2. 在树的深层点击几个树节点
   3. 保存点击后的 checkedTreeKeys
   4. 重新加载树（默认只加载第一层树节点）

问题是： 如何根据之前的checkedTreeKeys， 反选新加载的树？

**Comment by Leskd** [comment]
Reproduce step：
  1. dynamic render Tree ( only load the level one by default )
  2. then I checked some TreeNode in this tree
  3. save the checkedTreeKeys
  4. reload the tree  ( only load the level one by default )

my question is:  How do I reverse the newly loaded tree based on the previously checkedTreeKeys?

**Comment by zombieJ** [comment]
能给个代码重现吗？
http://codesandbox.io
