### ISSUE TITLE
 not supported by the `prop-types` package

### ISSUE THREAD

**Issue by colzz** [react-component/tree#195]
![2](https://user-images.githubusercontent.com/22288955/45069844-1a5a2880-b101-11e8-852b-a5c64b70b7b2.png)
![3](https://user-images.githubusercontent.com/22288955/45069845-1af2bf00-b101-11e8-8ad9-7ce4d1f0bf4c.png)
![1](https://user-images.githubusercontent.com/22288955/45069846-1af2bf00-b101-11e8-9b98-1b579b5b0b81.png)

**Comment by zombieJ** [comment]
Since react official package `prop-types` change the PropTypes logic. Old version react call will get the warning info. Pls update the react version instead.
