### ISSUE TITLE
Warning: '36753' does not exist in the tree.

### ISSUE THREAD

**Issue by rmccallum** [react-component/tree#196]
Hi,

Wrapping the RC-Tree in a component and passing down new props (list, checked keys and expanded keys) there are warnings thrown for every old list key.

Child component renders:

`
import React, {Component} from "react";
import Tree, {TreeNode} from 'rc-tree';
import "../assets/css/treeview.css";

export default class TreeView extends Component {

    constructor(props) {
        super(props);
        this.state = {
            expandedKeys: this.props.expandedKeys,
            checkedKeys: this.props.checkedKeys,
            list: this.props.list
        }
    }

    componentWillReceiveProps(nextProps) {
        if (nextProps.shouldTreeUpdate) {
            this.setState({checkedKeys: nextProps.checkedKeys, expandedKeys: nextProps.expandedKeys, list: nextProps.list});
        }
    };

    onExpand = (expandedKeys) => {
        this.setState({
            expandedKeys
        });
    };

    onNodeCheck = (checkedKeys) => {
        this.setState({
            checkedKeys,
        });
    };

    render() {
        const loop = data => {
            return data.map((item) => {
                if (item.children) {
                    return (
                        <TreeNode key={item.key}
                                  title={item.title}>
                            {loop(item.children)}
                        </TreeNode>
                    );
                }
                return <TreeNode key={item.key} title={item.title}/>;
            });
        };

        return <div>

            <Tree
                checkable
                onExpand={this.onExpand}
                expandedKeys={this.state.expandedKeys}
                onCheck={this.onNodeCheck}
                checkedKeys={this.state.checkedKeys}
            >
                {loop(this.state.list)}
            </Tree>
        </div>;
    }
}
`

And parent component will send new props:

`
<TreeView list={this.state.zips}
                                              expandedKeys={this.state.expandedZips}
                                              checkedKeys={this.state.checkedZips}
                                              tabName="Zips"
                                              shouldTreeUpdate={this.state.shouldTreeUpdate}
                                              onCheck={this.onOptionalCheck} />
`

Any help with this?

**Comment by zombieJ** [comment]
could you provide an online reproduce for this? https://codesandbox.io/

**Comment by rmccallum** [comment]
Trying codesandbox to create a pared-down app but getting errors when I use arrow functions:
` onExpand = expandedKeys => {
    console.log("--------", expandedKeys);
    this.setState({
      expandedKeys
    });
  };`

`/src/TreeView.js: Unexpected token (26:11)

  24 |   };
  25 | 
> 26 |   onExpand = expandedKeys => {
     |           ^
  27 |     console.log("--------", expandedKeys);
  28 |     this.setState({
  29 |       expandedKeys`

Any help with this?

**Comment by rmccallum** [comment]
So completed the demo with a 'fake API' call to refresh the list and checked keys when a button is pressed. It all works as expected.

I believe the issue lies with our implementation of the Redux Sagas updating different redux info at different times causing the re-render to happen and look for keys which do not exist.

Not an issue for this module.
