### ISSUE TITLE
Missing typings

### ISSUE THREAD

**Issue by mellis481** [react-component/tree#206]
I'm using the following package versions:

```
"rc-tree": "1.14.8"
"@types/rc-tree": "1.11.2",
```

I'm using the following code to define a tree:

```
const data = [
  { key: 1, title: 'Option 1' },
  {
    key: 2,
    title: 'Option 2',
    children: [
      { key: 21, title: 'Option 2.1' },
      { key: 22, title: 'Option 2.2' },
      { key: 23, title: 'Option 2.3' },
      { key: 24, title: 'Option 2.4' },
      { key: 25, title: 'Option 2.5' }
    ]
  }
];

<Tree treeData={data} />
```

I'm seeing the following compilation error:  

*Property 'treeData' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Tree> & Readonly<{ children?: ReactNode; }> & Readonly<TreeProps>'.*

**Comment by Rolando-Barbella** [comment]
I'm getting this too, there is a type missing on the TreeProps from index.d.ts, there should be something like:

```

export interface TreeProps {

 treeData: Array;
....

```

**Comment by zombieJ** [comment]
Hi,
We don't maintain `@types/rc-tree`. You can send a PR for it.
