### ISSUE TITLE
title不嵌套a标签的话ie9下不能拖拽

### ISSUE THREAD

**Issue by mraiguo** [react-component/tree#214]
我看到antd上的这个issue: https://github.com/ant-design/ant-design/issues/7460;
这里是说a标签内不能套a标签，所以不从rc-tree这一层修复。但是我看了一下，没有发现哪里有a标签啊？

**Comment by zombieJ** [comment]
以前版本的 Tree 默认是 a 标签，然后有个 issue 遇到的问题就是 title 里用了 a 标签导致报错。所以后来 TreeNode 就从 a 改成 span。这导致了 IE9 下拖拽就失效了。所以才需要用户自己在 title 里用 a 标签包一下哈。

**Comment by mraiguo** [comment]
@zombieJ  非常感谢，能问下 title 里用了 a 标签导致报错的issue在哪儿吗，我想看看防止以后出现这种错误，或者给个大概方向我去搜一下？

**Comment by zombieJ** [comment]
@mraiguo 之前找了一下，想不起来关键词了……
