### ISSUE TITLE
Can you add the selected style effect to the onRightClick of the Tree?

### ISSUE THREAD

**Issue by wangzhidavid** [react-component/tree#215]
"antd": "3.10.10",
"react": "16.2.0";
![default](https://user-images.githubusercontent.com/20512794/50512892-996bd600-0acf-11e9-8776-42eb682a6428.png)

谢谢！

**Comment by zombieJ** [comment]
你可以通过受控的方式来设置 `selectedKeys` 哈~

**Comment by wangzhidavid** [comment]
[直接给你一个动态图方便
![default](https://user-images.githubusercontent.com/20512794/50750834-c9f70100-1281-11e9-9dc2-e43e940bb6a4.gif)

**Comment by wangzhidavid** [comment]
谢谢了！找到原因，未设置Tree的selectedKeys，但是Tree组件有默认的selectedKeys值，导致设置右键选中虽设置，但是不起选中的效果。
