### ISSUE TITLE
Customized checkable ReactNode cannot get 'checked' props

### ISSUE THREAD

**Issue by Tracis** [react-component/tree#217]
If `Tree` is passed a customized checkable Component, the component will not get 'checked' state as below. 

```jsx
<Tree 
  treeData={defaultData}
  defaultExpandAll
  checkable={<Checkbox />}
  checkedKeys={this.state.checkedKeys}
  onCheck={this.handleCheck}
/>
```
`<Checkbox />` is a customized React Component.  But I will not get TreeNode checked state in `<Checkbox />`.

What is the correct way to use the `checkable` ?

**Comment by Tracis** [comment]
I have sew the source code. Customized checkable ReactNode cannot get the props from TreeNode.

This is the source code:

```jsx
renderCheckbox = () => {
    const { checked, halfChecked, disableCheckbox } = this.props;
    const { rcTree: { prefixCls, checkable } } = this.context;
    const disabled = this.isDisabled();

    if (!checkable) return null;

    // [Legacy] Custom element should be separate with `checkable` in future
    const $custom = typeof checkable !== 'boolean' ? checkable : null;

    return (
      <span
        className={classNames(
          `${prefixCls}-checkbox`,
          checked && `${prefixCls}-checkbox-checked`,
          !checked && halfChecked && `${prefixCls}-checkbox-indeterminate`,
          (disabled || disableCheckbox) && `${prefixCls}-checkbox-disabled`,
        )}
        onClick={this.onCheck}
      >
        {$custom}
      </span>
    );
  };
```

For the time being, I can only solve the problem through CSS.

**Comment by zombieJ** [comment]
Hi, [`checkable`](https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L336) support customize CheckBox is a legacy code that only keeps here for css checked status usage.

If you want to customize the checkbox, you can use `icon` for render. It pass full node props and accept ReactNode as function return.
