### ISSUE TITLE
Get root parent node in onSelect method

### ISSUE THREAD

**Issue by sehcheese** [react-component/tree#22]
I have made a tree with several layers of nesting. The `onSelect` property is on `<Tree>`, so I have to handle selection for any node in the same method. If I have selected a `<TreeNode>` that is several levels deep, I'd like to know the parent node at the root level from within the `onSelect` method. The parameters passed to this method are: 

> function(selectedKeys, e:{selected: bool, selectedNodes, node, event})

While inspecting the contents of `e` in the browser debugger, I was not able to find an immediate (or otherwise) way to access the parent node at the root level, or parent nodes in general. How can I do this? Thanks in advance.

**Comment by warmhug** [comment]
Do you just want find selected node's path to root? You can do it yourself. Or copy from here:
```js
function findPath(value, data) {
  const sel = [];
  function loop(selected, children) {
    for (let i = 0; i < children.length; i++) {
      const item = children[i];
      if (selected === item.value) {
        sel.push(item);
        return;
      }
      if (item.children) {
        loop(selected, item.children, item);
        if (sel.length) {
          sel.push(item);
          return;
        }
      }
    }
  }
  loop(value, data);
  return sel;
}
```
and similar demo is here: http://react-component.github.io/tree-select/examples/basic.html
![image](https://cloud.githubusercontent.com/assets/2011119/17093381/9150cf2a-527b-11e6-8353-81c83f91c264.png)
