### ISSUE TITLE
don't display node when node is filtered 

### ISSUE THREAD

**Issue by Jack47** [react-component/tree#23]
Can you guys implement this feature, just like the [tree-select filter demo](http://react-component.github.io/tree-select/examples/filter.html)?

**Comment by warmhug** [comment]
Why not use tree-select ?

**Comment by Jack47** [comment]
I don't want the selection box in `tree-select`, I want to render the checked item myself. Never mind, I already implement this feature outside of the tree component.

**Comment by kodram** [comment]
:+1:

**Comment by kodram** [comment]
@Jack47 how did you do this?
