### ISSUE TITLE
when updated rc-tree@2.1.1,can`t find index.css in the package assets.terrible

### ISSUE THREAD

**Issue by zhoufs1** [react-component/tree#263]
when updated rc-tree@2.1.1,can`t find index.css in the package assets.terrible

**Comment by vpckso** [comment]
I have the same problem

**Comment by komenank** [comment]
My understanding is that the index.css present in the example is a default one. Within the project, you can find an index.less in the assets folder that you can convert to css using the less package:

- install Less globally: `npm install -g less`

- convert index.less to index.css: `lessc index.less index.css`

- import your new index.css into your project

**Comment by atomicpages** [comment]
Please address this... It's unreasonable to expect consumers to _build_ component static resources.

**Comment by leojh** [comment]
an alternative is to use `less-loader` within your project

**Comment by komenank** [comment]
If you are using create-react-app, using `less-loader` would involve ejecting your project. That seems a bit much for stylesheet

**Comment by atomicpages** [comment]
Or if you use rollup, @babel/cli, tsc, pika-back, etc. `less-loader` won't work. @zombieJ  Can we please fix this package so there _aren't_ side effects?

**Comment by afc163** [comment]
https://github.com/react-component/footer/blob/f1863e86ebd29b8a999324864c2a632d089caa50/package.json#L34

**Comment by zombieJ** [comment]
Thanks @afc163 , updated: https://unpkg.com/browse/rc-tree@2.1.3/assets/
