### ISSUE TITLE
How can I use filterTreeNode

### ISSUE THREAD

**Issue by joseph-vedadi** [react-component/tree#264]
How can I filter the tree by string ?
I could not find any examples for : filterTreeNode

**Comment by joseph-vedadi** [comment]
@zombieJ  Could you please provide some examples Thanks

**Comment by zombieJ** [comment]
http://react-component.github.io/tree/examples/dropdown.html

**Comment by joseph-vedadi** [comment]
Thanks a lot, I got that working, yet it only bolds the found nodes. How can I make it to only show the found nodes?

**Comment by xiaogaofudao** [comment]
@joseph-vedadi i have the same problem. do you have any idea yet?

**Comment by iloveip** [comment]
I have the same problem. I would like to render only matched nodes in the tree and hide the unmatched ones. Is it possible to be done? Here is my question on [SO](https://stackoverflow.com/questions/64386466/filter-treenodes-in-ant-design-tree) and the link to [codesandbox](https://codesandbox.io/s/antd-tree-search-filter-lrv89?file=/index.js:0-3079).
