### ISSUE TITLE
How can I change the color of lines ?

### ISSUE THREAD

**Issue by joseph-vedadi** [react-component/tree#269]
My background is a little dark, and I cant see the lines. 
How can I change the color of the lines when the TreeNodes are expanded ... 

Thanks

**Comment by joseph-vedadi** [comment]
@zombieJ  Any idea?

**Comment by zombieJ** [comment]
You can override the default style:
https://unpkg.com/browse/rc-tree@3.0.0-alpha.15/assets/index.less
