### ISSUE TITLE
onCheck逻辑中的冗余

### ISSUE THREAD

**Issue by ClarkXia** [react-component/tree#27]
一个节点选中的时候 应该是只会影响自己的父节点和子节点  是不是没有必要遍历所有已选中的状态进行handleCheckState？

**Comment by warmhug** [comment]
父节点选中，也可能引起父节点的父节点全部选中，不需要遍历吗？

**Comment by ClarkXia** [comment]
初始化的时候的确需要遍历所有的设置节点，但是onCheck事件触发的选中  它应该只会影响的所有自己的子节点 和 所有自己的父节点   而我认为handleCheckState已经做到了这一步，按理说应该和取消选中的逻辑一样都只需要handleCheckState(this.treeNodesStates, [treeNode.props.pos], false);就可以

**Comment by warmhug** [comment]
是有个虚拟的单个“根”节点、只是没显示出来，感觉还是需要遍历到根节点的，欢迎 fork 一份按你自己想法做做看、如果没问题欢迎提 pr .
