### ISSUE TITLE
Multiple columns support

### ISSUE THREAD

**Issue by KvanSteijn** [react-component/tree#28]
Is it possible to support multiple columns in tree?

**Comment by warmhug** [comment]
Sorry, I can't understand what do you mean...

**Comment by KvanSteijn** [comment]
Table in tree view.
```
Title | Column 2 | Column 3 | Column 4 <- Columns
- A1    A2         A3         A4 <- Row
- B1    B2         B3         B4 <- Row
```
![multicolumntreeview](https://cloud.githubusercontent.com/assets/3213947/17922453/58c03526-69df-11e6-83e7-f3d12dd8f6d3.jpg)

**Comment by warmhug** [comment]
try http://react-component.github.io/table/examples/childrenIndent.html

**Comment by KvanSteijn** [comment]
Thank you for your response, but rc-table doesn't have drag and drop support?

**Comment by warmhug** [comment]
yes, it's a simple tree view in rc-table

**Comment by KvanSteijn** [comment]
Hmm. It's to basic for my, i need tree/table with drag and drop support.

**Comment by yesmeck** [comment]
Close as no actions can be token.
