### ISSUE TITLE
Big Data Error If Z More Than Six

### ISSUE THREAD

**Issue by crf444** [react-component/tree#29]
[http://react-component.github.io/tree/examples/big-data.html](url)

big data 在

x 2 y 1

z 只要 大于 6 选中就会出问题

比如 7 的时候就会有几个无法被选中或者现象特别奇怪

**Comment by warmhug** [comment]
感谢反馈，我会再测下

**Comment by crf444** [comment]
Thanks! ^_^

**Comment by yesmeck** [comment]
跟 #57 是同一个问题。
