### ISSUE TITLE
tree组件使用checkedKeys的时候checked点击无法更改状态

### ISSUE THREAD

**Issue by Sean-Snow** [react-component/tree#3]
使用checkedKeys动态checked时，鼠标点击 checked 没什么用啊

**Comment by warmhug** [comment]
http://react-component.github.io/tree/examples/checked.html  这里是有效的。不知道你那个是什么情况下的问题？希望描述仔细点

**Comment by Sean-Snow** [comment]
这个demo可以用，但是我放到我项目里面就不能用  checked

**Comment by Sean-Snow** [comment]
checkedbox再次点击的时候好像没用重新render

**Comment by Sean-Snow** [comment]
Tree 加了checkedKeys props 就不行了

**Comment by warmhug** [comment]
`checkable={true}` 这个设置是这样的吗？可以把你demo代码贴出来

**Comment by Sean-Snow** [comment]
<Tree ref='tree' openAnimation={animation} onCheck={this.onCheck}
        checkable defaultExpandAll checkedKeys={this.state.roleModuleIds}>{nodes}</Tree>

组件已经升级了，checkedKeys 可以用，但是使用checkedKeys 以后 checkbox就不能点击了

**Comment by afc163** [comment]
https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by yiminghe** [comment]
http://react-component.github.io/tree/examples/checked.html 例子不好，不要设置 defaultXX 了

2. 代码最好加下 https://github.com/react-component/menu/blob/0add01411b0fd65135b559a189f96ca3ce123008/src/Menu.jsx#L115 ,实现完全受控

**Comment by warmhug** [comment]
抱歉修复晚了点，请验证下
