### ISSUE TITLE
how to change icon 

### ISSUE THREAD

**Issue by lyquocnam** [react-component/tree#30]
hi author ! i see default icon is a folder, so how can i change to another one ?

**Comment by warmhug** [comment]
You can set your style with `rc-tree-iconEle` class.

**Comment by lyquocnam** [comment]
yep, but hard for me noob with stylesheet.
have anyways  we can set direct in treelist by props ?
`<Tree icon="/img/icon.png"></Tree>`
or
`<Tree icon="fa fa-home"></Tree>`
or same above in TreeNode:
```
<TreeNode icon="/img/icon.png"></TreeNode>
<TreeNode icon="fa fa-home"></TreeNode>
```

**Comment by warmhug** [comment]
show your code? https://jsfiddle.net/
