### ISSUE TITLE
onExpand

### ISSUE THREAD

**Issue by wttubes** [react-component/tree#32]
When is the onExpand fired? because somehow i don't see the console.log of the expand, i see the start, enter and drop events, but not the onExtand?

the tree is getting expanded, looks like the events just not fired.

**Comment by warmhug** [comment]
fire only on click these `switchers` 
![image](https://cloud.githubusercontent.com/assets/2011119/18084277/293a09ea-6ed9-11e6-813a-7e46f058c332.png)

**Comment by wttubes** [comment]
oh, i was getting the idea that the autoExpandParent is firing the onExpand function when dragged tree on hover the item, ok thanks.
