### ISSUE TITLE
@types/rc-tree is missing switcherIcon

### ISSUE THREAD

**Issue by fnielson1** [react-component/tree#320]
Typescript throws an error stating that `switcherIcon` isn't a prop on `<Tree>`

`<Tree switcherIcon={someFunc} />`

Can the `index.d.ts` file in @types/rc-tree be updated?

**Comment by afc163** [comment]
Don't use `@types/rc-tree`

**Comment by fnielson1** [comment]
This is not an option as I am using the types specified in `@types/rc-tree`. Such as `ExpandData`.

Without `@types/rc-tree` even this throws a Typescript error.

**Comment by afc163** [comment]
https://unpkg.com/browse/rc-tree@2.1.4/es/index.d.ts
