### ISSUE TITLE
Is it possible to set custom title (hover text)?

### ISSUE THREAD

**Issue by kelvinkoko** [react-component/tree#321]
For the "title" i mean the the html field "title" (for text show up on mouse hover)
Currently it is same as the name of file or folder.
is it possible to set a custom hover text?
<img width="720" alt="Screenshot 2020-05-01 at 9 36 28 AM" src="https://user-images.githubusercontent.com/2594899/80771803-879cb600-8b8f-11ea-996c-0476a0f97cec.png">
Thanks for the great library!~

**Comment by Dmitra** [comment]
Using custom node for a title with its html title does the job:
```
function Node (p) {
  return (
    <div title="Sheet">
    </div>
  )
}

function treeItem (item) {
  return {
    key: item.id,
    title: () => (<Node/>),
    children: _.map(item.children, treeItem),
  }
}

const treeData = treeItem(tree)

<TreeView
  treeData={[treeData]}
/>
```

**Comment by kelvinkoko** [comment]
Thanks, I will try it!~
