### ISSUE TITLE
documentation scroolbar

### ISSUE THREAD

**Issue by rodgomesc** [react-component/tree#323]
the documentation are not showing a scroolbar  for source code  even in chrome or firefox:

![image](https://user-images.githubusercontent.com/4893591/81077441-60adef00-8ec3-11ea-90f5-2421130b7a62.png)

**Comment by sandbox4013** [comment]
For temporary solution find `<code>` tag with devtools(ctrl+shift+c), than add `overflow: auto` to it.
![image](https://user-images.githubusercontent.com/49528851/82186466-973c2e80-98f3-11ea-8e2d-997c40e0c703.png)
