### ISSUE TITLE
Reactjs key props - Upgraded react version

### ISSUE THREAD

**Issue by paulchan** [react-component/tree#33]
Hi, Will this cause any issue with the component? https://facebook.github.io/react/warnings/special-props.html

It says that - "Most props on a JSX element are passed on to the component, however, there are two special props (ref and key) which are used by React, and are thus not forwarded to the component."

I've upgraded react to 15.3 and the tree component broke, it doesn't load the children nodes. Please kindly advice, thank you.

**Comment by warmhug** [comment]
I didn't find some issues on React@15.3
