### ISSUE TITLE
Does keyboard arrow key supported?

### ISSUE THREAD

**Issue by kelvinkoko** [react-component/tree#342]
I found this PR is merged to handle key down event and onKeyDown callback
https://github.com/react-component/tree/pull/275
But i seems cannot get it work and the README also haven't mention that. is it supported currently or i need to enable it?

**Comment by Dmitra** [comment]
yes, it works here https://react-component.github.io/tree/?path=/story/rc-tree--basic
you can put cursor into the top input and press TAB key - this would focus the rc-tree component and enable arrow keys navigation.

One thing I cannot understand is how to focus rc-tree component programmatically?

Even the hacky way:
```
  useEffect(() => {
    if (isFocused) {
      document.querySelector('.rc-tree input').focus()
    }
  })
```
doesn't make the component aware of being focused, i.e: assign `rc-tree-focused` class to the top element.

**Comment by challet** [comment]
Also, to programmaticaly focus it, you need to focus the hidden (0 height, 0 width) input with the following css selector :

```js
node.querySelectorAll('.rc-tree [role="tree"] input')[0].focus()
```

`node` being the top level element of the rendered tree.
