### ISSUE TITLE
how to change the icon for the node 

### ISSUE THREAD

**Issue by pvs560** [react-component/tree#35]
i passed icon attribute with image path as props to treeNode but the image is not displaying in the tree.

can you suggest how to add the custom icon for node in the tree

**Comment by warmhug** [comment]
Set `showIcon={false}` on Tree then set TreeNode's `title` prop to include your icon.

**Comment by deejross** [comment]
I just had a similar problem. I'm use Semantic UI React's `<Icon />` component for icons and was trying: `<Icon name="folder" /> + ' ' + item.name` but it would render `[Object Object] folder1`. I found this trick to work instead:

```javascript
function renderArray(arr) {
    return arr.map((comp, index) => <span key={index}>{comp}</span>);
}

let title = renderArray([<Icon name="folder" />, ' ', item.name]);
return <TreeNode key={item.key} title={title} />
```
