### ISSUE TITLE
treeData使用redux的数据数据更新后list不会自动刷新

### ISSUE THREAD

**Issue by JimZhang1028** [react-component/tree#364]
treeData使用redux的数据数据更新后list不会自动刷新，需要收一下父节点才再打开才会刷新。
<Tree
                        showLine={false}
                        showIcon={true}
                        onSelect={this.onSelect}
                        treeData={this.props.existTreeData}
/>

**Comment by yoyo837** [comment]
来个复现？

**Comment by JimZhang1028** [comment]
现在就卡在这的。就是这existTreeData给了初始值是一个树结构加载没问题。后面把existTreeData的某条改了。发现就不刷新。收起来再打开就是新的。`<Tree showLine={false} showIcon={true} onSelect={this.onSelect} treeData={this.props.existTreeData}/>`

**Comment by JimZhang1028** [comment]
redux写法有问题。
