### ISSUE TITLE
hao to use rc-tree with other module in webpack?

### ISSUE THREAD

**Issue by CoulDracula** [react-component/tree#37]
while i use rc-tree with other modules (such as react-fluxbox-grid ),i should make webpack as this :

```
{
        test: /(\.scss|\.css)$/,
        loaders: ['style', 'css?sourceMap&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!sass?sourceMap']
      }
```

then ,my rc-tree can not display checkbox and can not choose checkbox......

**Comment by warmhug** [comment]
It should not have this error. What happens if you don't have this setting?
