### ISSUE TITLE
Is there a direct way to get selected node (React component)?

### ISSUE THREAD

**Issue by Jeffwhen** [react-component/tree#39]
I know `selectedKeys` is available via `tree.state.selectedKeys`. But is there a way to get the node component of selected directly instead of iterate the whole tree to search a key match?

**Comment by warmhug** [comment]
See API doc 
![image](https://cloud.githubusercontent.com/assets/2011119/19546370/d5a5be76-96c1-11e6-9c75-98c63db66a21.png)

**Comment by Jeffwhen** [comment]
@warmhug That's a event API. What I mean is a query method. Like: 
```
let node = tree.getSelectedNode();
```

**Comment by warmhug** [comment]
React always has no get method.
