### ISSUE TITLE
[feature request] add option - renderSwitcher

### ISSUE THREAD

**Issue by haoxins** [react-component/tree#4]
场景: 动态加载节点的子节点, 当前节点没有子节点, 但是依旧 renderSwitcher, 点击加载子节点.

**Comment by yiminghe** [comment]
valid. @warmhug

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/10481615/4d684d36-72a4-11e5-98f7-678566694215.png)
新增两个API，需要实现个promise，参考[demo](http://react-component.github.io/tree/examples/dynamic.html)，感觉有不妥/建议，这里提出

**Comment by yiminghe** [comment]
async 可以去掉吧，有 onDataLoaded 就行了
