### ISSUE TITLE
Change Background Color for selected TreeNode

### ISSUE THREAD

**Issue by westede** [react-component/tree#400]
Hi there,

in the default settings of rc-tree the backgroundColor is by default a light yellow.
Is it possible, to change the color to a userdefinied color, like a light blue or something else?

Sorry for asking this, but i didn't find a solution in your docs.

Best
westede

**Comment by kayesn786** [comment]
Did you find any solution?

**Comment by westede** [comment]
> Did you find any solution?

No, we're still waiting for a response of the developers

**Comment by sundeep-adhikari** [comment]
you can overwrite the css see below
   .rc-tree-treenode {
                :hover {
                    background-color: ${theme.treeViewSelectedColor};
                  }

                  span.rc-tree-switcher {
                    background-image: none;
                  } 
                  span.rc-tree-node-selected {
                    background-color: ${theme.treeViewSelectedColor}; 
                    box-shadow: none;
                  }
              }
