### ISSUE TITLE
Indentation on tree levels not working

### ISSUE THREAD

**Issue by gustavomm19** [react-component/tree#417]
Hi! I am fetching data to my tree with de loadData prop, but when the data is displayed it looks like everything is on the same level.

`
<Tree
      checkable
      showIcon={true}
      onRightClick={onRightClick}
      loadData={onLoadData}
      treeData= {children}
  />
`

`
const onLoadData = async node => {

    if (node.type === 'children') {
      await axios
        .get(`api/trees/${node.entityId}/Location`)
        .then(async response => {
          console.log(response);

          response.data.childrenEntityList.map((child, index) => {
            node.children.push({
              ...child,
              machines: [],
              entityId: child.id,
              children: [],
              title: child.name,
              key: `${node.key}-${index}`,
              type: child.nodeType === 'Location' ? 'children' : 'machine',
              parent: node,
              isLeaf: child.hasMachines && child.hasChildrenLocations ? true : false,
            });
          });
        })
        .catch(error => {
          console.log(error.response);
          if (error.response) {
            console.log(error.response.data.errorMessage);
          } else {
            console.log('Cannot reach API');
          }
          throw new Error(error);
        });
    } else if (node.type === 'machine') {
      await axios
        .get(`api/trees/${node.entityId}/Machine`)
        .then(async response => {
          console.log(response);

          response.data.childrenEntityList.map((child, index) => {
            node.children.push({
              ...child,
              entityId: child.id,
              children: [],
              title: child.name,
              key: `${node.key}-${index}`,
              type: child.nodeType === 'Location' ? 'children' : 'machine',
              parent: node,
              isLeaf: child.hasMachines && child.hasChildrenLocations ? true : false,
            });
          });
        })
        .catch(error => {
          console.log(error.response);
          if (error.response) {
            console.log(error.response.data.errorMessage);
          } else {
            console.log('Cannot reach API');
          }
        });
    } 
  };

<Tree
      checkable
      showIcon={true}
      onRightClick={onRightClick}
      loadData={onLoadData}
      treeData= {children}
  />

`

**Comment by weihongliang233** [comment]
I encountered the same problem, did you solve it ?
