### ISSUE TITLE
Throws error when check tree nodes loaded dynamicly

### ISSUE THREAD

**Issue by superRaytin** [react-component/tree#43]
可重现 demo: http://codepen.io/superRaytin/pen/rWyEGd?editors=001

初步排查了下，这个问题跟 checkable 模式下 treeNodesState 有关，treeNodesState 在 render 时生成，但如果某些节点是动态生成的，就没有进入 treeNodesState，导致勾选时报错

```
Tree.js:252 Uncaught TypeError: Cannot set property 'checked' of undefined
```

**Comment by superRaytin** [comment]
重现步骤，点击 demo 中的 list 节点，list 下面的节点是动态生成的，勾选子节点就会报错了 @yiminghe @warmhug

**Comment by warmhug** [comment]
dynamic 用法和示例注意看下，不是这么用的。

![image](https://cloud.githubusercontent.com/assets/2011119/20524062/56f614d0-b0f3-11e6-86fc-555b1dae25b3.png)
