### ISSUE TITLE
TreeNode anchors prevent nested anchor DOM nodes

### ISSUE THREAD

**Issue by jbccollins** [react-component/tree#44]
https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L313

This line makes it invalid HTML to have an anchor as part of your title and causes a console warning if you try. For example if you want a title like 
```html
<a href="my/website/navigation">Go to our help pages!</a>
```
 you cannot do that. A simple quick fix is to just change that line to return a 
```html
<span>
```
 instead.

**Comment by yesmeck** [comment]
@warmhug 这里用 `<a>` 用什么特别的原因吗？

**Comment by warmhug** [comment]
为了支持 IE7/8 现在可以不用了

**Comment by jbccollins** [comment]
According to http://caniuse.com/usage-table IE7/8 combined account for less than 0.5% of all internet browser usage. Please don't let support for dead legacy browsers hold this library back.

**Comment by yesmeck** [comment]
PR is welcome. :D

**Comment by bkniffler** [comment]
https://github.com/react-component/tree/pull/86
