### ISSUE TITLE
能否支持子节点的双击操作

### ISSUE THREAD

**Issue by macisi** [react-component/tree#45]
比如双击子节点，打开对应的面板这样的交互场景

**Comment by warmhug** [comment]
可以自己绑定事件、再设置相应 expandedKeys 即可

**Comment by macisi** [comment]
ok. thx!

**Comment by aw6658913** [comment]
@macisi 请问后面你实现这个双击展开的功能了么

**Comment by lengfeng1224** [comment]
有个双击事件，看源码发现的，文档没有
<Tree
            showLine
            showIcon
            defaultExpandAll={true}
            onExpand={this.onExpand.bind(this)}
            expandedKeys={expandedKeys}
            autoExpandParent={autoExpandParent}
            onRightClick={this.onRightClick}
            onSelect={this.handle.bind(this)}
            onDoubleClick={this.dbClickToOpen.bind(this)}
          >
          {TreeNodes}
          </Tree>

**Comment by lengfeng1224** [comment]
```<Tree
            onDoubleClick={this.dbClickToOpen.bind(this)}
          >
          {TreeNodes}
          </Tree>```
