### ISSUE TITLE
error rc-tree@4.2.1: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by josh231101** [react-component/tree#472]
I have never gotten a similar problem, somehow this happened to me today. 
![image](https://user-images.githubusercontent.com/47585614/123836309-2d040480-d8cf-11eb-8947-0c23c83762e9.png)

**Comment by YongxinHou** [comment]
I have a similar issue as well. How should I do

**Comment by josh231101** [comment]
Hi @YongxinHou  well, we will have to update our Node to the LTS in order to avoid these problems. What you can do alternatively is getting back a stable version. Can you share to me your node version? Is the problem in your local machine or your deployed failed? 
If you want to search for a stable version
1. Install nvm (this allow you to rollback to any node version with the command nvm install 10.15.3)
2. Run your command to reinstall your deps, if you see the same error, well, search an antd version that allows you to continue. IN my case. **antd version 4.0.4 worked fine to me**

**Comment by taomas** [comment]
i have the same issue when deployed my project.

![image](https://user-images.githubusercontent.com/17002702/124436347-70b3ae00-dda8-11eb-8cae-b4064bb18754.png)

**Comment by YongxinHou** [comment]
Hi, I solved the problem and thanks to the author for quick reply. What I do is similar like what author suggests. I install nvm to upgrade my node version. In my case I upgrade my node version into 12.6.1 and problem is solved :> Hope it can help the others

**Comment by houxd1992** [comment]
that means we should use node 12+ for antd?  node 10+ is not support?

**Comment by josh231101** [comment]
> that means we should use node 12+ for antd? node 10+ is not support? @afc163

Yes, if your problem is locally it's very simple to install nvm and switch to a >=12.x Node version. If you are running out of time and your server is down, rollback your antd version to a specific one. Before pushing changes and run your pipeline to build Your project, do it locally, run yarn build or npm build and make sure that your Node version is compatible :)

**Comment by houxd1992** [comment]
I try to use a Lower version for rc-tree, it looks like ok. but i  don't know if there will be a problem :)
In antd docs, they still like that. @josh231101 
![image](https://user-images.githubusercontent.com/26320172/132618541-6f737104-2f02-48bc-b52f-79c5327a1502.png)
