### ISSUE TITLE
How to disable collapse expand functionality.

### ISSUE THREAD

**Issue by suniltak7** [react-component/tree#479]
Hello Team,

I need to remove collapse expand icon and functionality from grid but i am not able to figure it out the same.

Also want to show line for all items like showing in attached screenshot.

![issue12222](https://user-images.githubusercontent.com/88075977/128348961-455a16ee-b02c-4619-ba8e-f67313a93dc6.png)

**Comment by hnnweb** [comment]
Can you explain how you solved it?
