### ISSUE TITLE
Are TreeNodes editable?

### ISSUE THREAD

**Issue by Jeffwhen** [react-component/tree#48]
I see a edit and delete button on the demo site. It doesn't seen to work though.

**Comment by yesmeck** [comment]
@Jeffwhen  which demo?

**Comment by Jeffwhen** [comment]
[This demo](http://react-component.github.io/tree/examples/basic.html)
There's a edit button, an <a> actually. I clicked it, but nothing happended.
![screenshot](http://ww3.sinaimg.cn/large/0060lm7Tgw1fbfqnzpeb3j30cw063q3c.jpg)

**Comment by anton-aleksandrov** [comment]
@Jeffwhen check the code in the example, it shows custom labels, not the editable items

**Comment by Jeffwhen** [comment]
Anywat to implement editable tree?

**Comment by yesmeck** [comment]
Since TreeNode[title] can be any ReactElement, you can change the string title to a input dynamically. 

`<TreeNode title={<input type="text" />} key="0-0-0-1" />`

**Comment by Jeffwhen** [comment]
My opinion, make this feature integrated would be great.

**Comment by marcosfede** [comment]
please allow passing the leaf component that will be rendered as a prop

**Comment by nafg** [comment]
Please advertise this information more prominently
