### ISSUE TITLE
[feature request] Dynamic context menu to elements in the tree

### ISSUE THREAD

**Issue by gberth** [react-component/tree#5]
Would like to have the possibility on right-click (context-menu) to display possible actions related to the actual node. Callback to a function to get the right context-menu items and identifiers, or as a parameter to the TreeNode construction. Selected action would have to have function callback  like onSelect.

Right click would have to select the node, and display the context-menu.  Possible? :-)

**Comment by warmhug** [comment]
demo http://react-component.github.io/tree/examples/rightclick.html

**Comment by gberth** [comment]
Looks great.

Best regards
Gunnar

On Fri, Oct 23, 2015 at 12:54 PM, warmhug <notifications@github.com> wrote:

> demo http://react-component.github.io/tree/examples/rightclick.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/react-component/tree/issues/5#issuecomment-150542565>.
>



-- 
Mvh

Gunnar Berthelsen
91545192

**Comment by gberth** [comment]
Thanks :-)
