### ISSUE TITLE
BUG: dependencies "rc-util" ^5.0.0 需要更新至 ^5.8.0

### ISSUE THREAD

**Issue by spe-shun** [react-component/tree#509]
发现原因：升级 antd 4.17.2 webpack 编译报错 (yarn lock 未更新情况下)

Error Stack:
ERROR in ./node_modules/rc-tree/es/utils/treeUtil.js
Module not found: Error: Can't resolve 'rc-util/es/omit' in '(...)/node_modules/rc-tree/es/utils'
 @ ./node_modules/rc-tree/es/utils/treeUtil.js 6:0-35 111:56-60
 @ ./node_modules/antd/es/table/hooks/useSelection.js
 @ ./node_modules/antd/es/table/Table.js
 @ ./node_modules/antd/es/table/index.js
 @ ./node_modules/antd/es/index.js
(...)

位置: src/utils/treeUtil.ts
![image](https://user-images.githubusercontent.com/18157400/144559775-014de1a6-d60a-4c3d-af5a-0079a6733d74.png)

gitup 查看此文件添加版本
![image](https://user-images.githubusercontent.com/18157400/144559544-010e2226-c289-43a9-a5e2-818beb0dddf6.png)

**Comment by excellnn** [comment]
同样遇到这个问题
