### ISSUE TITLE
Performance issues when toggling the checkbox of a parent node with 100s of child/grandchild nodes

### ISSUE THREAD

**Issue by matthew-dalton-sirca** [react-component/tree#54]
When toggling the checkbox of a parent node with 100s of child/grandchild nodes, it can take several seconds (usually 2-3 seconds) before the result is rendered, which is not a good user experience.

Would it be possible for you to improve the performance of this operation?

More info: I am using the "checkedKeys" parameter for &lt;Tree&gt;, and I'm specifying only leaf nodes (ie. nodes with no children) in that parameter (as this makes my application logic much simpler).

**Comment by yesmeck** [comment]
Hello @matthew-dalton-sirca , sorry for late reply, could your provide a working code example?

**Comment by matthew-dalton-sirca** [comment]
Hi @yesmeck. We have solved our issue - it was not due to your library. I will close.
