### ISSUE TITLE
Hide checkbox on specific TreeNode (or to have it only for the leaf ones)

### ISSUE THREAD

**Issue by MV88** [react-component/tree#58]
Is it possible to obtain a tree like this?
![image](https://cloud.githubusercontent.com/assets/11991428/22547821/d2085c40-e943-11e6-8f00-8cd036e62d0d.png)
Basically I want to have the checkbox only when isLeaf={true}
I know i can disable it on those treenodes, but I want to hide it also or better **to Remove it** so it will not appear in the checkedKeys. 

Please le me know if I'm wrong opening this issue and if there are other channels for this kind of questions.
Thanks ahead of time!

**Comment by yesmeck** [comment]
Hello @MV88, you can set className on the parent nodes, then hide checkboxes by css.

**Comment by MV88** [comment]
Hi @yesmeck Thanks for answer. Maybe you can add a prop to TreeNode for hiding or even removing it from the DOM (I think it could be simpler). Anyway I'll do as you suggested :)
