### ISSUE TITLE
rc-tree does not ship with the image assets it requires

### ISSUE THREAD

**Issue by johnnyreilly** [react-component/tree#59]
Hi,

I've just noticed that the assets for rc-tree are not included with the component; instead they are links to a website called t.alipayobjects.com:

- https://github.com/react-component/tree/blob/master/assets/index.less#L49 - https://t.alipayobjects.com/images/T13BtfXl0mXXXXXXXX.gif
- https://github.com/react-component/tree/blob/master/assets/index.less#L77 - https://t.alipayobjects.com/images/T1.ANfXhXtXXXXXXXX.png
- https://github.com/react-component/tree/blob/master/assets/index.less#L82 - https://t.alipayobjects.com/images/rmsweb/T1YxhiXgJbXXXXXXXX.gif

I can work around this locally by manually downloading the assets and monkey-patching the css.  

However, it might be better for users of rc-tree that don't know they need to do this that the assets were included as part of the project.  It should just be a case of including them alongside the css.  

Do you have any thoughts about doing that?

**Comment by yesmeck** [comment]
Hello @johnnyreilly , it's hard to include images alongside the css, because each project will have different requirements for where to place images.

**Comment by johnnyreilly** [comment]
Thanks for responding @yesmek. The problem is, without the assets being included the component has a hard dependency on your website. It's true that different projects want to place images in different places but I don't think that's a problem. Why don't you include the images in the repo and then people can copy them to the location they desire? That's the approach that Bootstrap, Font Awesome etc take

**Comment by johnnyreilly** [comment]
BTW there is now a typescript definition for rc-tree: https://www.npmjs.com/package/@types/rc-tree

**Comment by yesmeck** [comment]
@johnnyreilly Here's my plan:

1. Include images in assets folder;
2. Encode images to base64 in CSS.

**Comment by johnnyreilly** [comment]
Sounds good!

**Comment by johnnyreilly** [comment]
Thanks!
