### ISSUE TITLE
delete treenode in data, how to change the checked keys state

### ISSUE THREAD

**Issue by xxShawn** [react-component/tree#62]
i use redux to manage the tree data, when i checked some node({checkedKeys: [1, 2, 3]}) then delete them in the store data, but the Tree's state checked keys are still there  ,how can i clear this state . i see the state getCheckedkeys from props is used inthe mounting time.  willrecieveprops is returned undefined.

**Comment by huumanoid** [comment]
Hello @xxShawn, are you sure you are using `checkedKeys` property to pass checked keys from redux? I've just tested it and it works fine.
**Note: you have to use `checkedKeys` property instead of `defaultCheckedKeys`**
