### ISSUE TITLE
Drag and drop leaves to other components?

### ISSUE THREAD

**Issue by vguarna** [react-component/tree#64]
Has anyone used this component for dragging leaf nodes to other components in an application? For example, I am looking to drag leaves into input boxes on another part of the screen.

**Comment by zombieJ** [comment]
Not support yet. react-dnd can help on this: https://github.com/react-dnd/react-dnd

**Comment by havenchyk** [comment]
@zombieJ hey, I see now `tree` supports dnd but without react-dnd. Why didn't you use it for `tree`?
