### ISSUE TITLE
Creating Trees within Trees

### ISSUE THREAD

**Issue by AchinthaReemal** [react-component/tree#65]
Is it possible to add Tree components as child components within another Tree.

i.e: something like this,  
```
<Tree>
  <TreeNode/>
  <Tree>
    <TreeNode/>
    <TreeNode/>
  </Tree>
</Tree>
```

**Comment by yesmeck** [comment]
No, you can't. Why do want to do that?

**Comment by AchinthaReemal** [comment]
I have a requirement where different trees require different behaviors. For an instance, there's a requirement to have certain parent nodes to check strictly while others check in the normal manner.

**Comment by yesmeck** [comment]
Sorry, not support such complex use case currently.
