### ISSUE TITLE
Drag and Drop Node to Root?

### ISSUE THREAD

**Issue by sallar** [react-component/tree#66]
Hi,

I'm using your great component in [Buttercup](https://github.com/buttercup-pw/buttercup). I have an issue. I'm unable to drag nodes to root. For example if I want to drag **Personal** or **Work** under Social Media to root, the "onDrop" event doesn't fire. Any ideas how to do that?

Thanks

![image](https://cloud.githubusercontent.com/assets/768052/23717260/c4cf348c-043b-11e7-9d78-a804bc082f79.png)

**Comment by yesmeck** [comment]
Hello @sallar , you should check `dropToGap` when handle `onDrop`, see this example https://github.com/react-component/tree/blob/83bc5e4ec9f0c8d1fd7cfd1aaf7e22473b89d09c/examples/draggable.js#L47-L61

**Comment by yesmeck** [comment]
> the "onDrop" event doesn't fire

You can increase the [drag gap](https://github.com/react-component/tree/blob/master/assets/index.less#L29-L38) to make the node more sensitive to drag event.

**Comment by sallar** [comment]
Thanks @yesmeck, I will try this. If it works then I'll close this if not I'll make a GIF of the issue. 👍

**Comment by yesmeck** [comment]
I've tried Buttercup, nice app. :)

**Comment by sallar** [comment]
Thanks! Im glad you tried it. @yesmeck :) It wouldn't be possible without your component! I dont know if I used it right though haha

**Comment by sallar** [comment]
@yesmeck increasing the drop gap didn't help. I can't drop the item to the root :( 

![buttercup](https://cloud.githubusercontent.com/assets/768052/23743428/3f298188-04b9-11e7-954c-e91526dd94b4.gif)

**Comment by yesmeck** [comment]
@sallar Three are two problems in your tree:

1. `onDrop` doesn't fire;
2. group can not be moved to root.

For the first problem you can increase the drop gap to solve it.

For the second problem, you must check `info.dropToGap` in onDrop handler, if  `info.dropToGap` exists, you should call something like `group.moveToRoot()` instead of `group.moveToGroup(parent)`.

**Comment by sallar** [comment]
@yesmeck I understand that, so you say I should "drop" the group on the first item in this list "General" and then check it's `info.dropToGap`? But then how do I prevent `rc-tree` from moving the group automatically "under" General?

**Comment by yesmeck** [comment]
Maybe I can send you a PR later. :D

**Comment by sallar** [comment]
@yesmeck I would appreciate that a lot :) Thanks!

**Comment by sallar** [comment]
@yesmeck If you wanted to send a PR, please use my `tree-root` branch, I have added some changes etc there: https://github.com/buttercup-pw/buttercup/tree/tree-root

**Comment by yesmeck** [comment]
@sallar 👌
