### ISSUE TITLE
Error in type activeKey

### ISSUE THREAD

**Issue by evgeniya-osmakova** [react-component/tree#663]
Now the type of activeKey is `Key`
But it also can be `null`

**Comment by yoyo837** [comment]
why it can be null?

**Comment by evgeniya-osmakova** [comment]
https://github.com/react-component/tree/blob/2ed2c0943a401e3155bdbf6a57cea08cbfde6980/src/Tree.tsx#L300
https://github.com/react-component/tree/blob/2ed2c0943a401e3155bdbf6a57cea08cbfde6980/src/Tree.tsx#L332
https://github.com/react-component/tree/blob/2ed2c0943a401e3155bdbf6a57cea08cbfde6980/src/Tree.tsx#L1192
