### ISSUE TITLE
Please release a new version to resolve TypeScript issues

### ISSUE THREAD

**Issue by kaiyoma** [react-component/tree#665]
See https://github.com/react-component/tree/issues/629 and https://github.com/react-component/tree/pull/636. Currently, rc-tree and anything that depends on it - like Ant Design - is incompatible with TypeScript 4.8 and 4.9. The fix is already in, and in fact was merged two months ago. Just make a release!

**Comment by yoyo837** [comment]
+ rc-tree@5.7.1

**Comment by kaiyoma** [comment]
Thank you! Can confirm the new release fixes the type checking issues.
