### ISSUE TITLE
动画效果导致渲染问题

### ISSUE THREAD

**Issue by zinkey** [react-component/tree#68]
![x](https://cloud.githubusercontent.com/assets/1016267/23939158/74d2ecc6-099a-11e7-8c61-fa73e1ccb523.gif)

控制模式下，点击部分节点，子节点会出现闪动。去掉rc-animate正常。是否可以提供不要动画的接口。

![image](https://cloud.githubusercontent.com/assets/1016267/23939261/de19ade6-099a-11e7-9883-769c4732cc87.png)

**Comment by zinkey** [comment]
```javascript
import { Tree } from 'antd';

const animation = {
  enter(node, done) {
    done();
  },
  leave(node, done) {
    done();
  },
  appear(node, done) {
    done();
  },
};

Tree.defaultProps.openAnimation = animation;
```

现在的做法。

**Comment by yesmeck** [comment]
你这个用的是 antd 还是 rc-tree？

**Comment by yesmeck** [comment]
能给个重现吗？http://codepen.io/benjycui/pen/KgPZrE?editors=001

**Comment by benjycui** [comment]
Close for no response.
