### ISSUE TITLE
title String/element

### ISSUE THREAD

**Issue by Frit** [react-component/tree#69]
Hi, doc says - title	desc: tree/subTree's title	type: String/element
I'm trying to add custom element with toggle button, tooltip etc. instead simple String title.
But when I added it dnd stopped work. Elements don't ract on mouse(even can't select text).

`<TreeNode key={item.id} title={<CustomTitle/>}  />` or
`<TreeNode key={item.id} title={<h1>Test</h1>}  />` (same issue)

**Comment by yesmeck** [comment]
@Frit Could provide a reproduce demo?

**Comment by Frit** [comment]
@yesmeck yes
try it without styles 
[https://gist.github.com/Frit](https://gist.github.com/Frit/dabb158e9bbaaaa9bf51367094b47b11)

**Comment by benjycui** [comment]
@Frit Please provide a re-producible demo: https://codepen.io/anon/pen/xLbmKm?editors=0010

**Comment by benjycui** [comment]
Online demo, actually, your gist doesn't work for we don't have `./util`.

**Comment by Frit** [comment]
sorry guys, I've chosen another lib, but this bug reproduces only on W7 (as I mentioned)

**Comment by Frit** [comment]
sorry guys, I've chosen another lib, but as I remember I've used ./util from this lib

**Comment by benjycui** [comment]
So just close now, until some developers meet this issue.
