### ISSUE TITLE
dinamically loading data

### ISSUE THREAD

**Issue by humbletrader** [react-component/tree#71]
Hi, 

In your dynamic example, I see that you are actually changing the state of your component inside the Promise, then you resolve the promise without sending any data. 
In my humble opinion, the correct approach would be to resolve the promise with the net tree data:

resolve(data); 

this way the data will get passed to the caller of your promise. 
Can you do something about that. I don't want for force state on my component.

**Comment by humbletrader** [comment]
The point is that you're not actually using the Promise mechanism. Do you ?

**Comment by yesmeck** [comment]
Yes, you are right.
