### ISSUE TITLE
npm install command shows some error 

### ISSUE THREAD

**Issue by Abdul-Hameed001** [react-component/tree#72]
while I give command **npm install** it shows some errors. Please let me know.

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: append-transform@^0.4.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.4.0, 0.3.0, 0.2.2, 0.2.1, 0.2.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'istanbul-lib-hook'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/.Trash/tree-master/npm-debug.log

**Comment by Abdul-Hameed001** [comment]
over come this error by using the command 

**npm install npm@latest -g**

which installs the dependencies

**Comment by Abdul-Hameed001** [comment]
when I give command npm start it's showing errors

> rc-tree@1.4.5 start /Users/apple/.Trash/tree-master
> rc-tools run server

sh: rc-tools: command not found

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! rc-tree@1.4.5 start: `rc-tools run server`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the rc-tree@1.4.5 start script 'rc-tools run server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rc-tree package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rc-tools run server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rc-tree
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rc-tree
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/apple/.Trash/tree-master/npm-debug.log

**Comment by paranoidjk** [comment]
caused by https://github.com/istanbuljs-archived-repos/istanbul-lib-hook/issues/10

**Comment by paranoidjk** [comment]
@Abdul-Hameed001 try again, it should been fixed

**Comment by Abdul-Hameed001** [comment]
I tried it again showing the same errors only
