### ISSUE TITLE
Empty directory shows up as a file

### ISSUE THREAD

**Issue by OmkarPh** [react-component/tree#736]
I have a treeData with empty directories (children: []), but it shows up as a file.

Is there any way to specify if a node should be rendered as directory or file explicitly ?

**Comment by OmkarPh** [comment]
Hi @MadCcc @zombieJ 
Can I try to fix this issue?

I am thinking of adding a prop, say `isLeafNode`
if `isLeafNode` is specified as true, then it is rendered as a leaf node 
otherwise, as usual it'll be dependent on number of children

**Comment by OmkarPh** [comment]
Thanks for adding ght option.
Closing this

**Comment by AyanSinhaMahapatra** [comment]
Thanks++ for adding this option and for the library, this has fixed the issue at at https://github.com/nexB/scancode-workbench/pull/604 :smile:
