### ISSUE TITLE
how to trigger expand of particular tree nodes other than defaultexpand

### ISSUE THREAD

**Issue by pvs560** [react-component/tree#75]
with the helps of expandedkeys can i trigger onExpand event of the tree.

**Comment by yesmeck** [comment]
Do you want trigger onExpand programmatically?

**Comment by pvs560** [comment]
yes how to trigger onExpand Programmatically

**Comment by yesmeck** [comment]
Could describe you use case, some background?

**Comment by pvs560** [comment]
right now manually when you click on the arrow icon only, then onExpand is triggered which will render the childrens under the tree. where as my usecase trigger the onExpand function without manually.

In rc-tree is there any parameter which takes the keys and expand the treenode?

**Comment by yesmeck** [comment]
Use `defaultExpandedKeys` or `expandedKeys` to specify expanded nodes. Note, these two props won't trigger onExpand. And I think trigger event programmatically is not a good pattern in React.

**Comment by pvs560** [comment]
my scenario is i have the items in breadcrum when i select any item in the breadcrum then tree should be expanded to that level.

will rc-tree support any prop. so,that update of that prop  will indirectly call on expand.

**Comment by yesmeck** [comment]
Then you can use `expandedKeys`.

**Comment by aicioara** [comment]
@yesmeck, can this behavior be trigger imperatively, rather than declaratively?
