### ISSUE TITLE
Any prop to get the checked title ? or checked value ?

### ISSUE THREAD

**Issue by lejema160** [react-component/tree#78]
There is a property to get the checked keys but I actually need to get the checked titles (they are different and they can't be change)
The key is a code and the title is a libelle ... and I need the libelle ! And can't swap them.
What do you think ?

Here is the code of my tree (2 levels, parents and leaves)

```
import React from 'react';
import Tree, { TreeNode } from 'rc-tree';
import 'rc-tree/assets/index.css';

export default class MyFiliereTree extends React.Component {
		
    render () {

    	const printLeaves = data => {
    		return data.map((item) => {
    			return (
    				<TreeNode key={item.id} title={item.libelleFr} />
    			);
    		});
    	};
    	
    	const printParents = data => {
    		return data.map((item) => {
    			if (item.sousFilieres.length > 0) {
    				return (
    					<TreeNode key={item.id} title={item.libelleFr}>
    						{printLeaves(item.sousFilieres)}
    					</TreeNode >
    					);
    			}
    			return <TreeNode key={item.id} title={item.libelleFr} />;
    		});
    	};

    	
        return (
            <div>
                <Tree className="myCls" showLine defaultExpandedKeys={["ALL"]} showIcon={false} checkable selectable={false} onCheck={this.props.onCheck} checkedKeys={this.props.checkedKeys}>
                	<TreeNode title="ALL" key="ALL">
                		{printParents(this.props.items)}
                	</TreeNode >
                </Tree >
            </div>
        )
    }

}
```

As you can see, a TreeNode as a key which is the item ID and a title which is the libelle of the item. I need to get the checked titles in my props it will help me so much

It's because I have a summary of the checked things but I need to print the titles, not the ID! People won't understand anything of the summary of their request if codes are written and not titles...

**Comment by yadavsunil00001** [comment]
Hey, i am also facing the same problem, if u able to solve anyhow just share the way to do the same.

**Comment by benjycui** [comment]
Nope, we are not going to provide this API, just map title from key.

```jsx
{
  [key]: title,
}
```
