### ISSUE TITLE
Does Keybored keys uparrow and downarrow  are supported for navigating levels in the tree

### ISSUE THREAD

**Issue by pvs560** [react-component/tree#79]
In rc-tree keyboard keys are supported (or) not for navigating levels in the tree.

**Comment by benjycui** [comment]
Nope, rc-tree doesn't support keyboard accessibility, but you can PR to improve it.

**Comment by pvs560** [comment]
i can help with the keyboard key support but needed some guidance

**Comment by Dmitra** [comment]
this is working now, as mentioned in the comment to #342
