### ISSUE TITLE
Filter Should Only Render Matched Nodes

### ISSUE THREAD

**Issue by efeminella** [react-component/tree#82]
Currently, the filterTreeNode implementation does not provide typical filtering behavior in that the Tree continues to render the unmatched nodes in addition to the matched nodes. There should, at a minimum, be an option to specify if unmatched nodes should be rendered as well.

**Comment by volodymyr-tsaryk** [comment]
Any update on this?
@efeminella were you able to work around this?

**Comment by GiordanoArman** [comment]
Hey there! @warmhug do you think this feature would be useful? I could try to implement it!

**Comment by warmhug** [comment]
ref http://react-component.github.io/tree-select/examples/basic.html, it implements a similar feature. But I don't think it's necessary to do it in Tree.

**Comment by GiordanoArman** [comment]
@warmhug cheers, I did not know about that module. Thanks for pointing it out!
