### ISSUE TITLE
Feature request - expand disabled nodes.

### ISSUE THREAD

**Issue by plandem** [react-component/tree#83]
There is no way to expand disabled nodes. Some times we need to disable some roots, but same time - be able to select child.

**Comment by jsbranco** [comment]
I submitted a PR with the ability to switch on/off the expand functionality on disabled nodes :
https://github.com/react-component/tree/issues/91

**Comment by benjycui** [comment]
@warmhug @yesmeck how about adding the following API:

## TreeNode

* expandable: whether the tree node is expandable
* selectable: whether the tree node is selectable
* checkable: whether the tree node is checkable
* disabled: if this is true, it means expandable=false, selectable=false, checkable=false

**Comment by warmhug** [comment]
@benjycui  Follow your heart ~~
