### ISSUE TITLE
onDragEnter event will be triggered dragging outside of Tree

### ISSUE THREAD

**Issue by kenyxy** [react-component/tree#84]
I integrate the Tree component in a portion of my application.
one issue that I enccounter is when I drag other component (such as image) outside of the Tree component it also cause the Tree component's onDragEnter event. as the dragged component is NOT inside of the Tree, "_this.dragNode_" is undefined then and will result in "_Uncaught TypeError: Cannot read property 'props' of undefined_" error

  Tree.prototype.onDragEnter = function onDragEnter(e, treeNode) {
    var enterGap = this.onDragEnterGap(e, treeNode);
    _if **(this.dragNode.props**.eventKey === treeNode.props.eventKey && enterGap === 0) {_
      this.setState({
        dragOverNodeKey: ''
      });
      return;
    }

"version": "1.4.5"

Thanks!

**Comment by benjycui** [comment]
Please provide a re-producible demo: https://codepen.io/anon/pen/xLbmKm?editors=0010
