### ISSUE TITLE
holdon a second before get expanded when dragging a node over.

### ISSUE THREAD

**Issue by kenyxy** [react-component/tree#85]
I have many TreeNodes and they are in deep enbeded, it is painful to drag the first one to drop into last one as a leaf, as the dragging will go through (drag over) many nodes between them and each of them will get expanded so that I have to drag over all of them to reach the last one. 

can I configure or use any hook (such as onDragOver) to let the TreeNode holdon a second before get expanded so that I can skip its child nodes?

"version": "1.4.5"

Thanks!

**Comment by Nico142** [comment]
This would be pretty helpful!
