### ISSUE TITLE
Customize drop area

### ISSUE THREAD

**Issue by fedexpando** [react-component/tree#87]
Is there any way to expand the area where you can drop nodes in the gap of a given node?.
The default is just too narrow for some users to hit.
I didn't find anything in the docs, but I hope there may be a hacky way to achive this or something.

Thank's 

![draganddropissue](https://cloud.githubusercontent.com/assets/8853478/25134405/db48c66a-2425-11e7-87a2-72d7509f2823.png)

**Comment by benjycui** [comment]
See: https://github.com/react-component/tree/issues/66#issuecomment-285237055
