### ISSUE TITLE
不能在TreeNode 上面添加自己的 组件

### ISSUE THREAD

**Issue by 6174** [react-component/tree#9]
比如我想为一个treeNode 添加一个删除的icon， 现在只能通过title 的方式修改内容
建议

1. title 模式 改为 TreeNode 添加自定义 children
2. title 可以以html 的方式 set

**Comment by warmhug** [comment]
title 里可以放任何合法的html（jsx）。比如 `title={<span style={{color: 'red'}}>sss</span>}`
