### ISSUE TITLE
点击动态生成的树节点的checkbox后报错

### ISSUE THREAD

**Issue by Maroon1** [react-component/tree#90]
# [Demo](https://codepen.io/maroon1/pen/OjYapY)

## 重现步骤
1. 点击 `新增树节点` 按钮
1. 勾选第一个树节点的checkbox
1. 点击 `新增树节点` 按钮
1. 勾选第二个树节点的checkbox，报错 `Uncaught TypeError: Cannot set property 'checked' of undefined`

**Comment by paranoidjk** [comment]
https://github.com/ant-design/ant-design/issues/1730

**Comment by paranoidjk** [comment]
@yesmeck @warmhug treeData 变化的时候没有重新计算 treeNodesStates，搜了下有很多以前的 issue，但看起来这个问题是没有解决好的？readme 里面写的 notice 也跟这个没什么关联的样子？

**Comment by Maroon1** [comment]
现在暂时的处理方式是，每次添加新的树节点都重新生成整棵树

**Comment by madadimy** [comment]
具体怎么做呢? issue看了很多  没有发现可行方案 @Maroon1

**Comment by he5310** [comment]
问题出在rc-tree下的 tree.js上面
删掉这个if判断就可以了,但是如果tree的数据比较复杂的话,删掉会有性能问题.
if (!props.loadData && this.checkKeys && this._checkedKeys && (0, _util.arraysEqual)(this._checkedKeys, checkedKeys)) {
          // if checkedKeys the same as _checkedKeys from onCheck, use _checkedKeys.
          checkKeys = this.checkKeys;
        } 
treeNode render的时候会判断当前state里面有没有checkedKeys,有的话,就不会走下面的else来更新treeNodesStates.

**Comment by he5310** [comment]
还有一点要注意的是树结构改变时需要清空checkedKeys,所以需要onCheck来手动维护checkedKeys.

**Comment by benjycui** [comment]
@Maroon1 你的 demo 链接 404 了，麻烦再重新提供个。我看下有没有修复了。

**Comment by Maroon1** [comment]
@benjycui 之前的那个 Demo 被我不小心删掉了，我有重新写了一个，那个问题依然存在
