### ISSUE TITLE
Deactivate auto expanding of tree nodes with children while dragging tree nodes

### ISSUE THREAD

**Issue by Nico142** [react-component/tree#93]
Hey,

is it possible to deactivate the auto expanding of tree nodes with children while dragging nodes over them? I only want to show the children from nodes which the user opened before he starts dragging. Also the 'rc-tree-switcher' shouldn't expand.

Thanks
Nico

**Comment by yesmeck** [comment]
No, it's not supported currently.

**Comment by benjycui** [comment]
@Nico142 https://github.com/react-component/tree/issues/85 is good enough.
