### ISSUE TITLE
树节点和checkbox为disabled时，但点击父节点仍然会改变

### ISSUE THREAD

**Issue by imdoge** [react-component/tree#99]
树节点设置为disabled，checkbox不可改变，但勾选父节点的checkbox全选/全不选时，仍然会影响到这个disabled的子树节点的checkbox，期待应该是不改变的吧

**Comment by jbccollins** [comment]
High priority for me :D

**Comment by paranoidjk** [comment]
Can you provide a reproducible demo?

**Comment by wall0313** [comment]
https://jsfiddle.net/wall0313/z5m01t49/
If a leaf checkbox is disabled, it should no longer belong to the parent tree. When we check/uncheck the parent checkbox, it would have no effect on the disabled leaf checkbox and the parent checkbox would be fully checked, even the disabled leaf checkbox is unchecked.

**Comment by jbccollins** [comment]
Yeah @wall0313's fiddle demonstrates the issue well

I think the best fix here would be to have a prop like "preventDisabledInteraction" which would do two things:

1) A disabled checkbox would not change it's checked status when its parent is checked or unchecked
2) The parent checkbox would not be in an 'halfChecked' or 'indeterminate' state when all enabled children are checked but disabled children are unchecked.

This prop would default to 'false' meaning that the current behavior would be default but users would be given the option to choose this alternative functionality.

**Comment by wall0313** [comment]
Any update?

**Comment by paranoidjk** [comment]
https://github.com/react-component/tree/blob/master/src/util.js#L177

@yesmeck @warmhug `disabled` 状态是存在 `TreeNode.props` 上的，全选的时候没有处理这个数据，如果要处理，还要对 props.children 做遍历，这个应该是设计上就没考虑好，disabled 应该和 checked 是一样的状态标识， 为什么不放在 data 上？
